### ISSUE TITLE
FramedRead::into_inner throws away buffered data

### ISSUE THREAD

**Issue by sid0** [alexcrichton/tokio-io#17]
(This is an issue with the current release version of tokio, but I decided to file it here since this looks like the future.)

More fun in my adventures with tokio :) I was trying to use `Framed::into_inner` and I found out that anything buffered gets thrown away. It would probably be worth adding a variant that returns a wrapper around the backing `Read` object that prepends whatever was buffered [here](https://github.com/alexcrichton/tokio-io/blob/master/src/framed_read.rs#L188).

**Comment by carllerche** [comment]
Could you elaborate on why you are unwrapping while there is still buffered data?

**Comment by sid0** [comment]
I'm doing that because I would like to change which decoder is being used for this data, and I'd also like to plug a `Read` adapter (in this case a bzip2, gzip or zstd decompressor) in between.

**Comment by carllerche** [comment]
An interesting data point, std `BufReader` has no way to get the buffer: https://doc.rust-lang.org/std/io/struct.BufReader.html

What are your thoughts @alexcrichton

**Comment by sid0** [comment]
I'd say that in general that's more defensible with `BufReader` because there's typically little reason to `into_inner` one.

**Comment by sid0** [comment]
This ended up being super easy to do with a forked copy of `Framed`, btw: https://gist.github.com/sid0/8d7e9225b45fb16d5b85250d50f377f9

**Comment by alexcrichton** [comment]
I'd probably recommend avoiding the use of `into_inner` here because shipping all the bytes around is gonna get pretty heinous pretty quickly. For a case where you may have multiple codecs I'd recommend something like

```rust
enum MyDecoder {
    Start(...),
    Bzip(...),
    Gzip(...),
    ...
}
```

And you just advance the state in `decode` from `Start` to a different state.

Now orthogonally I do think it may be useful to inspect the state of the buffer at some point, but given the lack of precedent in libstd we don't have much to go off unfortunately.

**Comment by carllerche** [comment]
I'm going to close this issue for now. I think that the suggestion above is good for your case and there also is the possibility to extract buffered up data in the `Decoder` itself.

**Comment by sid0** [comment]
(I'm still working with the last released versions of tokio-core, etc, so my terminology may not be fully up to date.)

> I'd probably recommend avoiding the use of into_inner here because shipping all the bytes around is gonna get pretty heinous pretty quickly.

In this case the maximum number of bytes we'll be copying around per parse is whatever the capacity of an `EasyBuf` is by default, which is around 8KB I believe. I don't feel too bad about that.

> For a case where you may have multiple codecs I'd recommend something like

So I do agree with this basic idea and it's what I'm doing in other places. However, decompression is fundamentally a bytestream to bytestream transformation that applies right before parsing. So I believe the right place to handle compression/decompression is not *within* the codec, but right *outside* it as a `Read` or `Write` adapter (just like it's done in your https://github.com/alexcrichton/flate2-rs package.)

I would love to show the code I'm writing, and at the moment it's planned to be open source but we're still a while away from getting all the legal formalities through.

Do you think you could at least provide an `into_inner_buffer` method that returns both the inner bytestream and whatever data was buffered? That will at least allow me to write my own adapter for this purpose and avoid having to maintain a local fork of the `Framed` adapter.

**Comment by alexcrichton** [comment]
@sid0 yeah I agree that this seems like it shoudl be before (or outside) a codec, but this issue is for a codec, right? 

Otherwise I'd imagine that you'd write a simple `AsyncRead -> AsyncRead` transformer which internally has a state machine for which compression algorithm to use.

**Comment by sid0** [comment]
I did consider that :) but unfortunately that doesn't work because of the internal buffering here.

If you look at which way data flows, it's something like:

```
AsyncRead (input bytestream) -> (1) -> FramedRead's internal buffer -> Codec -> framed output
```

(1) is a no-op to start, but it's where a decompressor would ideally be plugged in.

The problem with doing that is that the `FramedRead`'s internal buffer might have read too much, including some data that should have flowed through a decompressor plugged into (1). As far as I know there's no way to "push back" unread data from `FramedRead`'s internal buffer so that it can be passed into (1). That's basically what I'm asking for here.

**Comment by alexcrichton** [comment]
Oh my point is that if you insert it at (1) you don't have to deal with any internal buffers?

If you're decompressing you should be managing an internal buffer yourself, right?

(my thinking is that `FramedRead` calls your `read` function, not you decompressing data out of `FramedRead`'s buffer)

**Comment by sid0** [comment]
That's the thing, though -- I'm starting off by *not* decompressing at first, then based on the first few bytes of the input stream, switch to introducing decompressing afterwards. To make what I'm talking about more concrete, the input stream looks something like

```
00000000  48 47 32 30 00 00 00 0e  43 6f 6d 70 72 65 73 73  |HG20....Compress|
00000010  69 6f 6e 3d 42 5a 42 5a  68 39 31 41 59 26 53 59  |ion=BZBZh91AY&SY|
00000020  eb f0 26 a3 00 00 0e ff  ff fc be 47 20 44 23 7f  |..&........G D#.|
```

(It's part of the Mercurial wire protocol, in case you're interested.)

There's magic strings and stuff in the beginning, then a `Compression=BZ` header. At position `0x16` the input stream switches to compressed data, marked by the characteristic `BZ`magic string.

But `FramedRead` might read more than `0x16` bytes, right? This means that its internal buffer has the data the codec is interested about followed by some compressed data.

Now, sure, the codec can figure out that it should turn on a decompressor once it has read the header, but who or what is going to run the rest of the internal buffer (`0x16` onwards) through the decompressor?

**Comment by alexcrichton** [comment]
@sid0 so I'm pretty confused at this point. Above [you claimed](https://github.com/alexcrichton/tokio-io/issues/17#issuecomment-284886875) that this transformation sould happen *before* `FramedRead` (which I agree with). All of your comments though seem to indicate you're trying to use `FramedRead`?

Why can't this transformation happen where you like it? The `FramedRead` type can be created from any `AsyncRead + AsyncWrite` type, so if you're purely working with a wire protocol (no framing) then I'd recommend doing something like:

* Create a new wrapper struct (`HgDecode` or something like that)
* Implement `<T: AsyncRead> AsyncRead for HgDecode<T>`
* Implement the state machine internally in `HgDecode<T>` when read
* Call `framed` on `HgDecode<T>` which allows you to deal with raw decompressed bytes when framing.

Does that make sense?

**Comment by sid0** [comment]
Oh, so do the header decoding and compression switching within the HgDecode
wrapper around the AsyncRead, not within the decoder. Hmm, perhaps. I'll
see how practical that ends up being. Thanks.

**Comment by alexcrichton** [comment]
Yeah that's what I figured (and seems like the best location for this as well).

Lemme know how it goes though!

**Comment by illegalprime** [comment]
@alexcrichton I've been having trouble with this and with `std`'s `BufReader`, the solution so far being to add the option to decompose the `BufReader` into it's reader and buffer in a forked version of the `BufReader`: hyperium/hyper#1107.

I would really love to see this functionality in both `BufReader` and `Framed`, I see the solution you wrote, but this would complicated the API I have quite a bit. Basically I first have a handshake using hyper and making a codec which gives hyper requests doesn't implement `Sync`. Since the handshake is only a one time thing I'd rather not carry the weight of having both codecs in one and just move the byte buffer into the new codec.

Otherwise I've been having fun using `tokio`, cool stuff!

**Comment by alexcrichton** [comment]
@illegalprime I wonder, would https://github.com/tokio-rs/tokio-io/pull/45 cover your use case?

**Comment by illegalprime** [comment]
@alexcrichton other than a tiny edit, that is exactly what I need.
