### ISSUE TITLE
Clarify if AsyncWrite::shutdown implies flush or if flush should be called before shutdown

### ISSUE THREAD

**Issue by carllerche** [alexcrichton/tokio-io#24]
I am attempting to implement `shutdown`, but it is unclear if, after writing data to the inner writer (as part to shutdown) if I am expected to call `flush` or if I can call `shutdown` on the inner writer directly.

My assumption would be that a call to `shutdown` implies `flush`.

**Comment by alexcrichton** [comment]
Oh weird I thought I documented this, but I definitely agree, `shutdown` should imply `flush`
