### ISSUE TITLE
Potential bugs in codec::FramedRead

### ISSUE THREAD

**Issue by carllerche** [alexcrichton/tokio-io#8]
I'm a bit concerned about potential bugs introduced when porting FramedRead to use bytes::BytesMut.

`BytesMut` does no implicit allocation. Once the capacity of the buffer has been reached, it can no longer accept more data. This means that it could be possible for this call here to be passed a zero length buffer:

https://github.com/alexcrichton/tokio-io/blob/463e0365a556e1e12508d3b5ff811fc78b6d9750/src/framed_read.rs#L217

That would be interpreted as an EOF.

In general, how to deal w/ growing the buffer should be thought about. It's possible that growing the buffer should be left to the `Decoder` implementation, but may be unexpected...

**Comment by alexcrichton** [comment]
I figured we'd call `read_buf` if there's capacity available and otherwise grow the buffer, would that work?
